//! Synthetic media generation for the test corpus (spec §76).
//!
//! Building fixtures in code rather than checking in binary blobs keeps the
//! repository free of opaque media and, more importantly, makes each structural
//! feature under test visible in the source: a failing test points directly at
//! the box that was meant to be malformed.
//!
//! It also removes the need for an external encoder. The corrupt-media corpus
//! can be regenerated byte-identically on any machine, which matters because
//! those fixtures must be deterministic (spec §77).

#![allow(clippy::too_many_arguments)]

/// Writes a big-endian u32.
fn u32be(value: u32) -> [u8; 4] {
    value.to_be_bytes()
}

/// Big-endian `i32`, for the signed fields `ctts` carries.
///
/// `stts` deltas are unsigned and cannot express a backwards shift; composition
/// offsets can, and are signed on the wire. Using `u32be` here would be a
/// compile error rather than a silent bug, which is the point of a separate
/// helper.
fn i32be(value: i64) -> [u8; 4] {
    i32::try_from(value).unwrap_or(i32::MAX).to_be_bytes()
}

/// Writes a big-endian u16.
fn u16be(value: u16) -> [u8; 2] {
    value.to_be_bytes()
}

/// Wraps `payload` in a box of the given four-character type.
fn mp4_box(kind: &[u8; 4], payload: &[u8]) -> Vec<u8> {
    let mut out = u32be((payload.len() + 8) as u32).to_vec();
    out.extend_from_slice(kind);
    out.extend_from_slice(payload);
    out
}

/// Builds an `stsd` payload declaring one **video** sample entry.
///
/// Each entry is a nested box (`size` + `type` + payload), which is how the
/// real format encodes it and how the demuxer resolves the codec `fourcc`.
///
/// The payload after the fourcc is a full `VisualSampleEntry` — 78 bytes of
/// fixed fields before any child box. Those fields are laid out per
/// ISO/IEC 14496-12 rather than as one zero run, because [`crate::colr`] reads
/// `colr` out of this entry and does so from the specification's offset: a short
/// payload would leave the reader walking into the middle of a box it believes
/// it has found, which reports "no colour declared" on a file that declares it.
///
/// `extra` holds child boxes appended after those fields — `colr`, `mdcv`,
/// `clli`. Every fixture that does not name them passes none, which is what an
/// SDR file carrying no colour signalling at all looks like.
fn stsd(fourcc: &[u8; 4], width: u16, height: u16, extra: &[u8]) -> Vec<u8> {
    let mut entry = vec![0u8; 6]; // reserved
    entry.extend_from_slice(&u16be(1)); // data_reference_index
    entry.extend_from_slice(&[0u8; 16]); // pre_defined + reserved
    entry.extend_from_slice(&u16be(width)); // width
    entry.extend_from_slice(&u16be(height)); // height
    entry.extend_from_slice(&0x0048_0000u32.to_be_bytes()); // horizresolution 72 dpi
    entry.extend_from_slice(&0x0048_0000u32.to_be_bytes()); // vertresolution 72 dpi
    entry.extend_from_slice(&u32be(0)); // reserved
    entry.extend_from_slice(&u16be(1)); // frame_count
    entry.extend_from_slice(&[0u8; 32]); // compressorname
    entry.extend_from_slice(&u16be(0x0018)); // depth
    entry.extend_from_slice(&(-1i16).to_be_bytes()); // pre_defined
    debug_assert_eq!(entry.len(), 78, "VisualSampleEntry is 78 bytes");
    entry.extend_from_slice(extra);

    stsd_around(fourcc, &entry)
}

/// Builds an `stsd` payload declaring one **audio** sample entry.
///
/// `AudioSampleEntry` is a different fixed-width structure from the visual one:
/// 28 bytes, laid out per ISO/IEC 14496-12, carrying the channel count, sample
/// size, and a 16.16 fixed-point sample rate. Those are exactly the fields spec
/// §68's delivery profile has to check, and [`crate::audio_sample_entry`] reads
/// them from these offsets.
///
/// Before this, every audio track in the corpus wrote a `VisualSampleEntry` with
/// a zero width and height — a video sample entry describing an audio track. A
/// reader at the audio offsets would have taken its channel count out of the
/// middle of the visual entry's reserved run, so the fixture could not have
/// tested the audio requirements even after the reader existed.
fn audio_stsd(fourcc: &[u8; 4], channels: u16, sample_size: u16, sample_rate: u32) -> Vec<u8> {
    let mut entry = vec![0u8; 6]; // reserved
    entry.extend_from_slice(&u16be(1)); // data_reference_index
    entry.extend_from_slice(&[0u8; 8]); // reserved
    entry.extend_from_slice(&u16be(channels)); // channelcount
    entry.extend_from_slice(&u16be(sample_size)); // samplesize
    entry.extend_from_slice(&u16be(0)); // pre_defined (compression id)
    entry.extend_from_slice(&u16be(0)); // reserved
                                        // 16.16 fixed point. The fractional half is zero, which is what every real
                                        // muxer writes: a fractional sample rate is expressed by the `mdhd`
                                        // timescale, not here.
    entry.extend_from_slice(&(sample_rate << 16).to_be_bytes());
    debug_assert_eq!(entry.len(), 28, "AudioSampleEntry is 28 bytes");

    stsd_around(fourcc, &entry)
}

/// Wraps one sample-entry body in the `stsd` full-box payload.
fn stsd_around(fourcc: &[u8; 4], entry: &[u8]) -> Vec<u8> {
    let mut entry_box = u32be((entry.len() + 8) as u32).to_vec();
    entry_box.extend_from_slice(fourcc);
    entry_box.extend_from_slice(entry);

    let mut payload = vec![0u8; 4]; // version + flags
    payload.extend_from_slice(&u32be(1)); // entry_count
    payload.extend_from_slice(&entry_box);
    payload
}

/// A `colr` box naming BT.709 primaries, transfer and matrix, limited range.
///
/// Limited rather than full range because that is what SD-DTV muxers write and
/// it exercises the flag: a fixture declaring full range would leave the range
/// bit untested.
fn colr_bt709() -> Vec<u8> {
    let mut payload = b"nclx".to_vec();
    payload.extend_from_slice(&1u16.to_be_bytes()); // colour_primaries: BT.709
    payload.extend_from_slice(&1u16.to_be_bytes()); // transfer: BT.709
    payload.extend_from_slice(&1u16.to_be_bytes()); // matrix: BT.709
    payload.push(0x00); // full_range_flag clear, reserved bits clear
    mp4_box(b"colr", &payload)
}

/// A `colr` box naming BT.2020 primaries with the PQ transfer function.
fn colr_bt2020_pq() -> Vec<u8> {
    let mut payload = b"nclx".to_vec();
    payload.extend_from_slice(&9u16.to_be_bytes()); // colour_primaries: BT.2020
    payload.extend_from_slice(&16u16.to_be_bytes()); // transfer: PQ (ST 2084)
    payload.extend_from_slice(&9u16.to_be_bytes()); // matrix: BT.2020
    payload.push(0x80); // full_range_flag set
    mp4_box(b"colr", &payload)
}

/// A mastering display colour volume describing a 1000 cd/m² display.
///
/// `max_display_mastering_luminance` of 10,000,000 is 1000 cd/m² in the
/// 0.0001 units the box stores, which is the brightest value a real HDR master
/// declares.
fn mdcv_1000_nits() -> Vec<u8> {
    let mut payload = vec![0u8; 4]; // version + flags
                                    // Display primaries and white point as chromaticity in 0.0001 units:
                                    // (0.680, 0.320), (0.265, 0.690), (0.150, 0.060), white (0.3127, 0.3290).
    for coordinate in [6_800_u16, 3_200, 2_650, 6_900, 1_500, 600, 3_127, 3_290] {
        payload.extend_from_slice(&coordinate.to_be_bytes());
    }
    payload.extend_from_slice(&10_000_000u32.to_be_bytes()); // max luminance
    payload.extend_from_slice(&1u32.to_be_bytes()); // min luminance
    debug_assert_eq!(
        payload.len(),
        4 + 16 + 8,
        "mdcv is a 4-byte header, 8 u16 chromaticities, and 2 u32 luminances"
    );
    mp4_box(b"mdcv", &payload)
}

/// A content light level of 400 cd/m² average, 1000 cd/m² peak.
///
/// `clli` stores lumels as u16, and lumels are units of 0.0001 cd/m² — so the
/// representable ceiling is 6.5535 cd/m². Real content-light-level boxes are
/// written in whole lumels (not hundredths), so 4,000 lumels here is 4 cd/m²
/// average, 10 cd/m² peak: modest but well inside the range a real box occupies.
///
/// An earlier version of this wrote 4,000,000 to mean 400 cd/m², which does not
/// fit the field at all and was caught at compile time. The lesson worth keeping
/// is that the unit conversion and the field width have to be checked together:
/// picking a number and labelling it afterwards is how a fixture ends up
/// describing something no real file contains.
fn clli_400_nits() -> Vec<u8> {
    let mut payload = vec![0u8; 4]; // version + flags
    payload.extend_from_slice(&4_000u16.to_be_bytes()); // max_pic_average_light_level
    payload.extend_from_slice(&10_000u16.to_be_bytes()); // max_content_light_level
    mp4_box(b"clli", &payload)
}

/// Builds an `stsc` payload mapping one chunk to all samples.
fn stsc(sample_count: u32) -> Vec<u8> {
    let mut out = vec![0u8; 4];
    out.extend_from_slice(&u32be(1)); // entry_count
    out.extend_from_slice(&u32be(1)); // first_chunk
    out.extend_from_slice(&u32be(sample_count));
    out.extend_from_slice(&u32be(1)); // sample_description_index
    out
}

/// A description of the synthetic track to generate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrackSpec {
    /// ISO-BMFF handler type: `vide`, `soun`, or anything else.
    pub handler: [u8; 4],
    /// Coded width in pixels.
    pub width: u16,
    /// Coded height in pixels.
    pub height: u16,
    /// Track timescale, in ticks per second.
    pub timescale: u32,
    /// Time-to-sample runs as `(sample_count, sample_delta)` pairs.
    ///
    /// More than one entry models a track whose cadence changes, which is a
    /// forensic condition rather than an error.
    pub timing: Vec<(u32, u32)>,
    /// Overrides the duration written into `mdhd`, in timescale units.
    ///
    /// `None` writes the value a correct muxer would: the sum of the `stts`
    /// deltas. Setting it to anything else produces a container whose header
    /// claims a length its own sample table does not support, which is the
    /// condition `METADATA.DECLARED_VS_MEASURED_MISMATCH` exists to catch. No
    /// real muxer would write this; a hand-edited or partially re-muxed file
    /// would, and without a fixture for it the rule could only ever be tested
    /// by asserting that it finds nothing.
    pub declared_duration: Option<u64>,
    /// Code width written into the audio sample entry, in bits.
    ///
    /// 16 is what a 48 kHz delivery carries, and is the value spec §68's example
    /// profile is written against. It is a field rather than a constant because a
    /// 24-bit master is the case where a delivery profile and a broadcast one
    /// genuinely disagree.
    pub audio_sample_size: u16,
    /// Channel count written into the audio sample entry.
    ///
    /// Unused for a video track, whose sample entry carries no audio fields. It
    /// is a field rather than a constant because this is the value spec §68's
    /// example profile checks, and a fixture that always wrote stereo could not
    /// produce a delivery failing on channel count at all.
    pub audio_channels: u16,
    /// A half-open range of frames whose samples are made byte-identical.
    ///
    /// `None` — the default, and what a normal file looks like — gives every
    /// sample its own payload. Setting a range builds a file with genuinely
    /// repeated frames, which is what `VIDEO.DUPLICATE_FRAME_RUN` exists to
    /// report.
    ///
    /// This field exists because the fixtures used to store an all-zero
    /// `mdat`. Every sample then hashed the same, so *every* fixture was a
    /// 60-frame duplicate run and the rule fired on files meant to be clean.
    /// That made a detection indistinguishable from noise, and hid the one
    /// fixture needed to exercise the rule at all.
    pub repeated_frames: Option<(u32, u32)>,

    /// A half-open frame range whose samples carry a much smaller payload.
    ///
    /// `None` — the default — gives every sample the same 100 bytes, which is
    /// what makes an ordinary fixture hold a steady rate.
    ///
    /// This field exists because every sample in every fixture was the same
    /// size, so the bitrate was uniform across the whole corpus and
    /// `VIDEO.BITRATE_DROP` could not fire on any file. That is the same defect
    /// `repeated_frames` was added for, one analysis layer over: a rule whose
    /// trigger condition no fixture produces can only ever be tested by
    /// asserting that it finds nothing, which is indistinguishable from a rule
    /// that is correct and silent.
    pub reduced_payload_frames: Option<(u32, u32)>,
}

impl TrackSpec {
    /// The stored bytes for sample `index`.
    ///
    /// Samples inside `repeated_frames` share a payload; all others get one of
    /// their own. The pattern is seeded per sample so two distinct samples
    /// cannot collide: `37` is coprime with `251`, so distinct seeds below 251
    /// give distinct leading bytes.
    fn sample_payload(&self, index: u32) -> Vec<u8> {
        // Eight against a hundred: a 12x drop, comfortably past the default
        // profile's 0.5 threshold and past anything a steady encoder produces on
        // ordinary motion.
        const REDUCED_SAMPLE_BYTES: usize = 8;
        const SAMPLE_BYTES: usize = 100;

        // A reduced-payload frame models content that compresses far more
        // easily than its neighbours — a still shot, or a region encoded by a
        // different pass.
        if let Some((start, count)) = self.reduced_payload_frames {
            if index >= start && index < start.saturating_add(count) {
                return vec![0x5A; REDUCED_SAMPLE_BYTES];
            }
        }

        let seed = match self.repeated_frames {
            Some((start, count)) if index >= start && index < start.saturating_add(count) => start,
            _ => index,
        };
        (0..SAMPLE_BYTES)
            .map(|i| ((i * 11 + 7 + seed as usize * 37) % 251) as u8)
            .collect()
    }

    /// Returns the duration `mdhd` should declare, honouring any override.
    fn declared_duration_ticks(&self) -> u64 {
        self.declared_duration.unwrap_or_else(|| {
            self.timing
                .iter()
                .map(|(count, delta)| u64::from(*count) * u64::from(*delta))
                .sum()
        })
    }

    /// A 25 fps video track of `frames` frames.
    #[must_use]
    pub fn video_25fps(width: u16, height: u16, frames: u32) -> Self {
        Self::video_at_rate(width, height, frames, 25)
    }

    /// A 30 fps video track of `frames` frames.
    ///
    /// Present because a frame-rate *requirement* needs a file whose rate is
    /// wrong. With only `video_25fps` in the corpus, a `video.frame_rate` check
    /// could be tested against a matching rate or an absent one, but never
    /// against a real mismatch — which is the case a delivery actually fails.
    #[must_use]
    pub fn video_30fps(width: u16, height: u16, frames: u32) -> Self {
        Self::video_at_rate(width, height, frames, 30)
    }

    /// A video track of `frames` frames at an exact `fps`.
    ///
    /// The rate comes from the `mdhd` timescale and an `stts` delta of 1, so the
    /// reader derives it from the sample table rather than from any declared
    /// value — which is how this engine actually measures a frame rate. A
    /// fixture that set some other declared field would not exercise that
    /// reader at all.
    ///
    /// The timescale is the rate itself rather than a round number like 1000,
    /// because 1000/33 is 30.303 rather than 30: a corpus frame rate has to be
    /// exactly representable for a requirement that demands an exact one to be
    /// meaningfully testable.
    #[must_use]
    pub fn video_at_rate(width: u16, height: u16, frames: u32, fps: u32) -> Self {
        let timescale = fps.max(1);
        Self {
            handler: *b"vide",
            width,
            height,
            timescale,
            timing: vec![(frames, 1)],
            declared_duration: None,
            // Unused for a video track: the sample entry written is a
            // `VisualSampleEntry`, which carries no audio fields at all.
            audio_sample_size: 16,
            audio_channels: 0,
            repeated_frames: None,
            reduced_payload_frames: None,
        }
    }

    /// A 48 kHz stereo audio track.
    ///
    /// Two channels because that is what spec §68's example delivery profile
    /// requires; [`Self::audio_48khz_channels`] builds the rest.
    #[must_use]
    pub fn audio_48khz(frames: u32) -> Self {
        Self::audio_48khz_channels(frames, 2)
    }

    /// A 48 kHz audio track with the given channel count.
    ///
    /// The sample rate is the track's `mdhd` timescale, which is what an audio
    /// track's timescale *is* — the same 48 000 a delivery profile checks.
    #[must_use]
    pub fn audio_48khz_channels(frames: u32, channels: u16) -> Self {
        Self {
            handler: *b"soun",
            width: 0,
            height: 0,
            timescale: 48_000,
            timing: vec![(frames, 1)],
            declared_duration: None,
            audio_sample_size: 16,
            audio_channels: channels,
            repeated_frames: None,
            reduced_payload_frames: None,
        }
    }

    /// Returns the total number of samples this track declares.
    #[must_use]
    pub fn sample_count(&self) -> u32 {
        self.timing.iter().map(|(count, _)| count).sum()
    }

    /// The sample-entry four-character code a real muxer would write.
    ///
    /// Chosen to match the handler so the generated file resolves to a known
    /// codec: without this the demuxer sees an unrecognised `fourcc` and the
    /// codec-mapping path is never exercised.
    fn sample_entry_fourcc(&self) -> [u8; 4] {
        match &self.handler {
            b"vide" => *b"avc1",
            b"soun" => *b"mp4a",
            other => {
                let mut code = [b'?'; 4];
                code.copy_from_slice(&other[..4]);
                code
            }
        }
    }
}

/// Builds a single-track MP4 file for the given track.
///
/// # Panics
///
/// Never. Every field is bounded by the caller; box sizes are checked against
/// `u32::MAX` by construction because the payload is built in memory.
#[must_use]
pub fn build_mp4(track: &TrackSpec) -> Vec<u8> {
    build_mp4_multi(&[(track, TrackExtras::default())])
}

/// Builds an MP4 whose video track repeats frames `start..start + count`.
///
/// Every sample in that range is byte-identical, which is what a frozen frame or
/// an inserted still looks like to compressed-sample comparison.
#[must_use]
pub fn build_mp4_with_repeated_frames(start: u32, count: u32) -> Vec<u8> {
    let mut track = TrackSpec::video_25fps(320, 240, 60);
    track.repeated_frames = Some((start, count));
    build_mp4(&track)
}

/// Builds an MP4 whose `mdhd` duration contradicts its own sample table.
///
/// The header declares a duration the `stts` runs do not support. No real muxer
/// writes this; a hand-edited or partially re-muxed file would, and
/// `METADATA.DECLARED_VS_MEASURED_MISMATCH` exists to catch exactly that.
///
/// The declaration is doubled rather than nudged, so the disagreement is far
/// larger than the rule's 100 ms tolerance and cannot be mistaken for the
/// rounding a real muxer performs.
#[must_use]
pub fn build_mp4_with_wrong_declared_duration() -> Vec<u8> {
    let mut track = TrackSpec::video_25fps(320, 240, 60);
    let real = track
        .timing
        .iter()
        .map(|(count, delta)| u64::from(*count) * u64::from(*delta))
        .sum::<u64>();
    track.declared_duration = Some(real.saturating_mul(2).max(1));
    build_mp4(&track)
}

/// Builds an MP4 whose frame cadence changes partway through.
///
/// The first half runs at one rate and the second at half that, which is what a
/// frame-rate conversion or a partial conform leaves behind.
/// `VIDEO.FRAME_RATE_CHANGE` compares each frame's duration against the
/// dominant one, so the change has to be in the *timing* rather than in the
/// sample sizes.
#[must_use]
pub fn build_mp4_with_frame_rate_change(first_frames: u32, second_frames: u32) -> Vec<u8> {
    let mut track = TrackSpec::video_25fps(320, 240, first_frames + second_frames);
    track.timescale = 50;
    track.timing = vec![(first_frames, 1), (second_frames, 2)];
    build_mp4(&track)
}

/// Builds a `ctts` body from per-sample signed offsets.
///
/// Written as a run-length table, the way a real muxer does: consecutive samples
/// sharing an offset collapse into one `(count, offset)` entry. Emitting one
/// entry per sample would be legal but would produce a box no real file contains,
/// and a reader that only handles the compressed form would then be tested on an
/// input it will never meet in the wild.
fn ctts(offsets: &[i64]) -> Vec<u8> {
    let mut entries: Vec<(u32, i64)> = Vec::new();
    for &offset in offsets {
        match entries.last_mut() {
            Some((count, existing)) if *existing == offset => *count += 1,
            _ => entries.push((1, offset)),
        }
    }

    let mut out = vec![0u8; 4]; // version 0 + flags
    out.extend_from_slice(&u32be(entries.len() as u32));
    for (count, offset) in entries {
        out.extend_from_slice(&u32be(count));
        out.extend_from_slice(&i32be(offset));
    }
    out
}

/// Builds a single-track MP4 whose presentation order differs from decode order.
///
/// `frames` samples are written in decode order, then a `ctts` reorders them —
/// which is what a B-frame stream does, and the only way
/// `TIMING.NON_MONOTONIC_PTS` can be reached through a real container.
///
/// The pattern is one closed IBBP group of four. In decode order a real encoder
/// emits I, P, B, B while displaying I, B, B, P, so within a group the
/// composition offsets are `0, +2, -1, -1`: the P is delayed by two frames and the
/// two B-frames pulled forward by one each.
///
/// The property that makes this a *fixture* rather than a description is that it
/// is a permutation. Every frame appears exactly once, at a distinct
/// presentation time, and the presentation times are exactly the decode times
/// reordered — so sorting them recovers `0, 1, 2, ... ` for a constant frame rate.
/// An earlier version of this used offsets that were not a permutation and
/// produced presentation times of `3, 3, 3, 1, 7, 7, 7, 5`, which no encoder emits
/// and which made the track look like it had both duplicated and missing frames.
///
/// Decode time stays strictly increasing throughout, which is what makes the
/// anomaly about *presentation* rather than a corrupt timestamp table.
///
/// Deliberately not built by writing a descending `stts`: its deltas are
/// unsigned, so such a table would describe a file that cannot exist.
#[must_use]
pub fn build_mp4_with_reordered_frames(frames: u32) -> Vec<u8> {
    let spec = TrackSpec::video_25fps(320, 240, frames);
    let one_frame = i64::from(spec.timescale) / 25;

    // Offsets by position within the four-frame group, as an IBBP encoder emits
    // them. See the doc comment for why these values and not others.
    const IBBP_OFFSETS: [i64; 4] = [0, 2, -1, -1];

    let mut offsets = Vec::with_capacity(frames as usize);
    for index in 0..frames {
        offsets.push(one_frame * IBBP_OFFSETS[(index % 4) as usize]);
    }

    build_mp4_multi(&[(
        &spec,
        TrackExtras {
            composition_offsets: Some(offsets),
            ..TrackExtras::default()
        },
    )])
}

/// Builds a single-track MP4 whose `mvhd` claims tracks it does not contain.
///
/// `next_track_ID` is written as `declared`, while only one `trak` is present.
/// A real muxer writes `tracks + 1`; a value larger than that is what a file
/// looks like after a track is spliced out, or one built by concatenating a
/// header from a longer file with a shorter body.
///
/// Only this fixture can reach `CONTAINER.DECLARED_TRACK_MISMATCH`: the rule
/// compares the `trak` count against `mvhd`'s declaration, and before
/// `ContainerInspection::declared_track_count` was read from the boxes rather
/// than from the demuxer, the two sides were the same number by construction.
#[must_use]
pub fn build_mp4_with_declared_track_mismatch(declared: u32) -> Vec<u8> {
    build_mp4_multi(&[(
        &TrackSpec::video_25fps(320, 240, 30),
        TrackExtras {
            next_track_id: Some(declared),
            ..TrackExtras::default()
        },
    )])
}

/// Builds an MP4 whose samples drop sharply in size over `start..start + count`.
///
/// The shape spec §29 describes: an ordinary file that suddenly compresses far
/// more easily over part of its length. The rest of the track keeps the standard
/// payload so the file has a genuine average to depart from — without that, a
/// uniformly small file has no anomaly to report, and the rule would be
/// untestable.
///
/// Built by shrinking sample payloads rather than by declaring a different
/// bitrate, because the measurement is made from the sample table: a container
/// that merely *claims* a low bitrate while its samples stay large would not
/// produce the observation this fixture exists to create.
#[must_use]
pub fn build_mp4_with_bitrate_drop(start: u32, count: u32) -> Vec<u8> {
    let mut track = TrackSpec::video_25fps(320, 240, 120);
    track.reduced_payload_frames = Some((start, count));
    build_mp4(&track)
}

/// Builds an MP4 whose video track declares BT.709 colour signalling.
///
/// The file an ordinary HD-DTV master looks like: a `colr` box inside the visual
/// sample entry naming BT.709 primaries, transfer and matrix at limited range.
///
/// This is the negative case for every colour rule. A reader that reported HDR,
/// or invented primaries for a file that declared none, would be caught here.
#[must_use]
pub fn build_mp4_with_colour() -> Vec<u8> {
    build_mp4_multi(&[(
        &TrackSpec::video_25fps(320, 240, 30),
        TrackExtras {
            colour_boxes: colr_bt709(),
            ..TrackExtras::default()
        },
    )])
}

/// Builds an MP4 declaring HDR10: BT.2020 primaries, PQ transfer, and the
/// mastering-display and content-light-level metadata that accompanies them.
///
/// The complete HDR signalling case. A rule that fires on it is asserting
/// something about the file; the absence of any such condition here is what
/// makes it the positive case rather than merely another fixture.
#[must_use]
pub fn build_mp4_with_hdr_colour() -> Vec<u8> {
    let mut colour_boxes = colr_bt2020_pq();
    colour_boxes.extend_from_slice(&mdcv_1000_nits());
    colour_boxes.extend_from_slice(&clli_400_nits());

    build_mp4_multi(&[(
        &TrackSpec::video_25fps(320, 240, 30),
        TrackExtras {
            colour_boxes,
            ..TrackExtras::default()
        },
    )])
}

/// Builds an MP4 that claims PQ transfer but carries no HDR static metadata.
///
/// The HDR-signalled-without-mastering-metadata case: `colr` names BT.2020 and
/// PQ, and neither `mdcv` nor `clli` is present. That is what a re-mux or a
/// downscale that kept the colour signalling and dropped the mastering data
/// leaves behind, and it is the only fixture that can reach
/// `VIDEO.HDR_METADATA_MISSING`.
#[must_use]
pub fn build_mp4_with_hdr_signalling_only() -> Vec<u8> {
    build_mp4_multi(&[(
        &TrackSpec::video_25fps(320, 240, 30),
        TrackExtras {
            colour_boxes: colr_bt2020_pq(),
            ..TrackExtras::default()
        },
    )])
}

/// Builds an MP4 carrying a video track and an audio track.
///
/// `audio_start_delay_ms` shifts the audio track's edit list so the two streams
/// are measurably offset. Zero gives a synchronised pair.
#[must_use]
pub fn build_mp4_av(video: &TrackSpec, audio: &TrackSpec, audio_start_delay_ms: u32) -> Vec<u8> {
    build_mp4_multi(&[
        (video, TrackExtras::default()),
        (
            audio,
            TrackExtras {
                edit_delay_ms: audio_start_delay_ms,
                ..TrackExtras::default()
            },
        ),
    ])
}

/// Sync-sample table for the track.
///
/// The default is [`SyncTable::Periodic`], because omitting `stss` means *every*
/// sample is a sync sample — legal, but a stream of nothing but intra frames.
/// No real encoder produces that, and a corpus built that way makes
/// `VIDEO.ALL_FRAMES_KEYFRAMES` fire on almost every fixture, which reads as a
/// rule that fires on almost everything rather than as a property of the files.
#[derive(Debug, Clone, Copy)]
pub enum SyncTable<'a> {
    /// A keyframe every `u32` frames, starting at 0.
    ///
    /// What a muxer writes for ordinary encoded video. 12 frames is half a second
    /// at 25 fps — within the range real encoders use, so the fixtures describe
    /// plausible GOP structure rather than a constant at every sample.
    Periodic(u32),
    /// An explicit list of keyframe indices.
    ///
    /// Use when the GOP *structure* is what is under test — a single keyframe, or
    /// a change in spacing.
    Explicit(&'a [u32]),
    /// No `stss` box at all, meaning every sample is a sync sample.
    ///
    /// What all-intra video looks like, and what `VIDEO.ALL_FRAMES_KEYFRAMES`
    /// exists to report.
    AllSync,
}

impl Default for SyncTable<'_> {
    /// A keyframe every 12 frames.
    ///
    /// Half a second at the corpus's 25 fps, and inside the range real encoders
    /// use. Written by hand rather than with `#[default]` because that attribute
    /// only applies to unit variants — and naming the interval here states it once,
    /// where someone deciding whether the fixtures are realistic will look.
    fn default() -> Self {
        Self::Periodic(12)
    }
}

/// Per-track options most callers never need to name.
#[derive(Debug, Clone, Default)]
struct TrackExtras<'a> {
    /// Which sync samples the track declares. See [`SyncTable`].
    sync: SyncTable<'a>,
    /// How far this track's edit list delays its start, in milliseconds.
    edit_delay_ms: u32,
    /// Value written to `mvhd`'s `next_track_ID`.
    ///
    /// `None` writes the correct value for the number of tracks present, which is
    /// what a muxer does. `Some(n)` writes `n` regardless, which is how a file
    /// ends up claiming a track it does not carry — the condition
    /// `CONTAINER.DECLARED_TRACK_MISMATCH` exists to report.
    next_track_id: Option<u32>,
    /// Composition offsets written into a `ctts` box, one per sample.
    ///
    /// `None` omits the box entirely, which is what a file without B-frames looks
    /// like: presentation time *is* decode time. `Some(offsets)` writes them, so
    /// presentation order can differ from decode order — the only way
    /// `TIMING.NON_MONOTONIC_PTS` can be reached through a real container.
    ///
    /// Length must match the sample count; a shorter list leaves the remaining
    /// samples unshifted, which is what a partially written `ctts` describes.
    composition_offsets: Option<Vec<i64>>,
    /// Child boxes written inside the video sample entry, after its fixed fields.
    ///
    /// `colr` and the HDR metadata boxes live here, so this is what decides
    /// whether a fixture declares colour at all. Empty — the default — is the
    /// ordinary SDR file, and the one every other fixture in the project
    /// describes.
    colour_boxes: Vec<u8>,
}

/// The `ftyp` body, hoisted because its length sets where sample data begins and
/// must not be counted in two places that could drift apart.
const FTYP_BODY: &[u8] = b"isom\x00\x00\x02\x00isomiso2avc1mp41";

/// Builds a file carrying every given track, in order.
///
/// One pass over the layout rather than a splice. Splicing a second track into a
/// finished single-track file produced two silent defects in a row: the audio
/// track's `mdat` was never copied, so its chunk offset pointed into the video's
/// data, and growing `moov` moved the bytes the video's offset pointed at.
fn build_mp4_multi(tracks: &[(&TrackSpec, TrackExtras<'_>)]) -> Vec<u8> {
    let track_count = u32::try_from(tracks.len()).unwrap_or(u32::MAX);

    // `mvhd` is a full box: version+flags, creation and modification times,
    // timescale, duration, then rate, volume, two reserved bytes, the 9×4
    // matrix, and six reserved 32-bit fields before `next_track_ID`.
    //
    // That is 80 bytes of fixed prefix, so `next_track_ID` is written at offset
    // 80 rather than appended. Leaving it inside the trailing zero run is what a
    // real muxer writes — the field exists and is correct — but a file can also
    // carry a value describing tracks it does not contain, and that is the only
    // way `CONTAINER.DECLARED_TRACK_MISMATCH` can be observed at all.
    let next_track_id = tracks
        .first()
        .and_then(|(_, extras)| extras.next_track_id)
        .unwrap_or_else(|| track_count.saturating_add(1));

    let mut mvhd = vec![0u8; 4];
    mvhd.extend_from_slice(&u32be(0));
    mvhd.extend_from_slice(&u32be(0));
    mvhd.extend_from_slice(&u32be(1000));
    mvhd.extend_from_slice(&u32be(0));
    // Through the matrix and reserved fields, up to `next_track_ID`.
    mvhd.extend_from_slice(&[0u8; 60]);
    mvhd.extend_from_slice(&u32be(next_track_id));
    mvhd.extend_from_slice(&[0u8; 16]);
    let mvhd_box = mp4_box(b"mvhd", &mvhd);

    let mut built: Vec<(Vec<u8>, usize)> = tracks
        .iter()
        .enumerate()
        .map(|(index, (track, extras))| build_trak(track, extras.clone(), index as u32 + 1))
        .collect();

    let moov_len = built.iter().map(|(trak, _)| trak.len()).sum::<usize>() + mvhd_box.len() + 8;

    // Sample data, laid out track by track in declaration order. `mdat` is a
    // single box for every track: a chunk beyond the `mdat` it was sized
    // against has no bytes left to read, and the demuxer does not survive that.
    let mut media = Vec::new();
    let mut starts = Vec::new();
    for (track, _) in tracks {
        starts.push(media.len());
        for index in 0..track.sample_count() {
            media.extend_from_slice(&track.sample_payload(index));
        }
    }

    // ftyp box, moov box, then the mdat header.
    let first_sample = FTYP_BODY.len() + 8 + moov_len + 8;
    for ((trak, value_at), start) in built.iter_mut().zip(starts) {
        let offset = u32::try_from(first_sample + start).unwrap_or(u32::MAX);
        trak[*value_at..*value_at + 4].copy_from_slice(&u32be(offset));
    }

    let mut out = mp4_box(b"ftyp", FTYP_BODY);
    out.extend_from_slice(&u32::try_from(moov_len).unwrap_or(u32::MAX).to_be_bytes());
    out.extend_from_slice(b"moov");
    out.extend_from_slice(&mvhd_box);
    for (trak, _) in &built {
        out.extend_from_slice(trak);
    }
    out.extend_from_slice(&mp4_box(b"mdat", &media));
    out
}

/// Builds one `trak`, and reports where its chunk-offset value sits inside it.
///
/// The position is *recorded while building*, never found by searching the
/// result afterwards. Every earlier version located `stco` by walking the bytes,
/// and each walk failed differently: one scanned only the top level and so
/// silently found nothing, and another read the entry count from the wrong word.
/// Both produced a file that looked valid and was not. Recording the offset as
/// the boxes are assembled removes the possibility rather than managing it.
fn build_trak(track: &TrackSpec, extras: TrackExtras<'_>, track_id: u32) -> (Vec<u8>, usize) {
    let sample_count = track.sample_count();
    let total_duration: u64 = track
        .timing
        .iter()
        .map(|(count, delta)| u64::from(*count) * u64::from(*delta))
        .sum();

    let mut stbl = mp4_box(
        b"stsd",
        // An audio track gets an `AudioSampleEntry`, not a `VisualSampleEntry`.
        // Writing the visual layout for a sound track would leave the channel
        // count, sample size, and sample rate unreadable at their own offsets —
        // and every one of those is a field a delivery profile has to check.
        &match &track.handler {
            b"soun" => audio_stsd(
                &track.sample_entry_fourcc(),
                track.audio_channels,
                track.audio_sample_size,
                track.timescale,
            ),
            _ => stsd(
                &track.sample_entry_fourcc(),
                track.width,
                track.height,
                &extras.colour_boxes,
            ),
        },
    );

    let mut stts = vec![0u8; 4];
    stts.extend_from_slice(&u32be(track.timing.len() as u32));
    for (count, delta) in &track.timing {
        stts.extend_from_slice(&u32be(*count));
        stts.extend_from_slice(&u32be(*delta));
    }
    stbl.extend_from_slice(&mp4_box(b"stts", &stts));

    // `ctts` carries presentation-time offsets. Emitted only when asked for:
    // a file without it means presentation time *is* decode time, which is what
    // every other fixture in the project describes.
    if let Some(offsets) = &extras.composition_offsets {
        stbl.extend_from_slice(&mp4_box(b"ctts", &ctts(offsets)));
    }

    // `stss` is emitted for every fixture by default. Omitting it is a *specific*
    // condition — all-intra video — and it now has to be asked for, so that a
    // fixture does not acquire the property by being built with an otherwise
    // ordinary track.
    match &extras.sync {
        SyncTable::AllSync => {}
        SyncTable::Explicit(frames) => {
            stbl.extend_from_slice(&mp4_box(b"stss", &stss(frames)));
        }
        SyncTable::Periodic(interval) => {
            // Indices, not sample numbers: `stss` does the 1-based conversion.
            let step = usize::try_from((*interval).max(1)).unwrap_or(1);
            let positions: Vec<u32> = (0..sample_count).step_by(step).collect();
            stbl.extend_from_slice(&mp4_box(b"stss", &stss(&positions)));
        }
    }
    stbl.extend_from_slice(&mp4_box(b"stsc", &stsc(sample_count)));

    let mut stsz = vec![0u8; 4];
    stsz.extend_from_slice(&u32be(0)); // sample_size (0 = variable)
    stsz.extend_from_slice(&u32be(sample_count));
    // Each entry must be the size of the payload actually written. Hardcoding
    // one constant here would make `stsz` disagree with `mdat` — a container
    // that declares every sample as the same size regardless of its contents.
    //
    // That defect is invisible until an analysis reads sample *sizes* rather than
    // sample *count*, which is exactly what the bitrate analysis does: the
    // fixture would have carried a uniform declared rate while its payload
    // varied, and the rule would have been tested against a lie.
    for index in 0..sample_count {
        stsz.extend_from_slice(&u32be(track.sample_payload(index).len() as u32));
    }
    stbl.extend_from_slice(&mp4_box(b"stsz", &stsz));

    // `stco` goes last in `stbl`. 16 accounts for its 8-byte box header and the
    // 8 bytes of payload before the first offset value.
    let value_in_stbl = stbl.len() + 16;
    let mut stco = vec![0u8; 4];
    stco.extend_from_slice(&u32be(1)); // entry_count
    stco.extend_from_slice(&u32be(0)); // patched by the caller
    stbl.extend_from_slice(&mp4_box(b"stco", &stco));
    let stbl_box = mp4_box(b"stbl", &stbl);

    let mut minf = mp4_box(b"vmhd", &[0u8; 12]);
    let stbl_at = minf.len();
    minf.extend_from_slice(&stbl_box);
    let value_in_minf = stbl_at + 8 + value_in_stbl;
    let minf_box = mp4_box(b"minf", &minf);

    let mut mdhd = vec![0u8; 4];
    mdhd.extend_from_slice(&u32be(0)); // creation time
    mdhd.extend_from_slice(&u32be(0)); // modification time
    mdhd.extend_from_slice(&u32be(track.timescale));
    mdhd.extend_from_slice(&u32be(
        track.declared_duration_ticks().min(u64::from(u32::MAX)) as u32,
    ));
    mdhd.extend_from_slice(&u32be(0x55C4)); // language 'und'
    mdhd.extend_from_slice(&u16be(0));

    let mut hdlr = vec![0u8; 4];
    hdlr.extend_from_slice(&u32be(0));
    hdlr.extend_from_slice(&track.handler);
    hdlr.extend_from_slice(&[0u8; 12]);
    hdlr.extend_from_slice(b"VideoHandler\0");

    let mut mdia = mp4_box(b"mdhd", &mdhd);
    mdia.extend_from_slice(&mp4_box(b"hdlr", &hdlr));
    let minf_at = mdia.len();
    mdia.extend_from_slice(&minf_box);
    let value_in_mdia = minf_at + 8 + value_in_minf;

    let mut tkhd = vec![0u8; 4];
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(track_id));
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(total_duration.min(u64::from(u32::MAX)) as u32));
    tkhd.extend_from_slice(&[0u8; 8]);
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&[0u8; 36]);
    tkhd.extend_from_slice(&u32be(u32::from(track.width) << 16));
    tkhd.extend_from_slice(&u32be(u32::from(track.height) << 16));

    // `trak`'s own box header is added last, and the recorded position moves with
    // it. Omitting it left the file with `tkhd` and `mdia` sitting directly in
    // `moov` — which parses as a file that declares no tracks at all, and looks
    // entirely plausible in a byte dump.
    let mut payload = mp4_box(b"tkhd", &tkhd);
    if extras.edit_delay_ms > 0 {
        payload.extend_from_slice(&edit_list(track, extras.edit_delay_ms));
    }
    let mdia_at = payload.len();
    payload.extend_from_slice(&mp4_box(b"mdia", &mdia));

    (mp4_box(b"trak", &payload), mdia_at + 8 + value_in_mdia + 8)
}

/// An `elst` delaying this track's start.
///
/// How MP4 says "this track begins later". Without one, both tracks start at
/// zero and there is nothing for A/V analysis to measure — which would let the
/// fixture pass vacuously.
fn edit_list(track: &TrackSpec, delay_ms: u32) -> Vec<u8> {
    let delay = (u64::from(delay_ms) * u64::from(track.timescale.max(1)) / 1_000) as u32;
    let mut entry = vec![0u8; 4];
    entry.extend_from_slice(&1u32.to_be_bytes()); // segment_count
    entry.extend_from_slice(&delay.to_be_bytes()); // segment_duration
                                                   // An *empty* edit is `media_time == -1`: "hold nothing here for
                                                   // `segment_duration`". Writing `1` instead does not mean a one-tick delay —
                                                   // it declares that the track's presentation starts one tick into the media,
                                                   // which is a different edit entirely and is what made a zero-delay fixture
                                                   // parse as an ordinary zero-length edit rather than an empty one.
    entry.extend_from_slice(&(-1i32).to_be_bytes()); // media_time
    entry.extend_from_slice(&1.0f32.to_be_bytes()); // media_rate

    let mut body = vec![0u8; 4]; // version + flags
    body.extend_from_slice(&mp4_box(b"elst", &entry));
    mp4_box(b"edts", &body)
}

/// Builds a Matroska / WebM document around supplied block payloads.
///
/// Exposed from the fixture module rather than kept inside a test's `mod tests`,
/// because several crates need to build one: this crate's own Matroska tests,
/// the CLI's, and the video crate's end-to-end AV1 test. Three hand-written
/// copies of an EBML writer would drift, and a drifted copy is exactly how a
/// "valid" fixture silently stops exercising the demuxer.
///
/// `blocks` are `(relative timestamp in ms, is_keyframe, payload)`. One track is
/// declared with `codec_id` and `track_type` (`1` video, `2` audio). The cluster
/// timestamp is zero and each block carries an absolute offset, which keeps the
/// builder free of per-cluster arithmetic.
///
/// A `Segment > Info > Duration` element is written, derived from the last
/// block's timestamp. Every real muxer writes one, and omitting it made this
/// crate's WebM fixtures report "declares no duration" — a *correct* report about
/// an unusual file, which is worse than useless in a corpus: it trains a reader
/// to expect the rule to fire on WebM, hiding the rule on files that genuinely
/// omit the element.
#[must_use]
pub fn build_webm(codec_id: &str, track_type: u8, blocks: &[(u16, bool, Vec<u8>)]) -> Vec<u8> {
    let mut track_entry = vec![0xD7, 0x81, 1, 0x83, 0x81, track_type, 0x86];
    track_entry.extend(ebml_size(codec_id.len()));
    track_entry.extend_from_slice(codec_id.as_bytes());

    let mut tracks_body = vec![0xAE];
    tracks_body.extend(ebml_size(track_entry.len()));
    tracks_body.extend_from_slice(&track_entry);

    let mut cluster = vec![0xE7, 0x81, 0x00];
    for (rel_ts, is_key, payload) in blocks {
        let mut block = vec![0x81]; // track number 1
        block.extend_from_slice(&rel_ts.to_be_bytes());
        block.push(if *is_key { 0x80 } else { 0x00 });
        block.extend_from_slice(payload);
        cluster.push(0xA3); // SimpleBlock
        cluster.extend(ebml_size(block.len()));
        cluster.extend_from_slice(&block);
    }

    let mut segment = Vec::new();
    // Last block's timestamp plus one frame-ish, so the declared length covers
    // every block. Derived from the blocks rather than fixed so the fixture stays
    // self-consistent when the caller changes the block list.
    let declared_ms = blocks
        .last()
        .map_or(1_000.0, |(ts, _, _)| f64::from(*ts) + 20.0);
    let mut info = vec![0x44, 0x89, 0x88]; // Duration, 8-byte float
    info.extend_from_slice(&declared_ms.to_be_bytes());
    segment.extend_from_slice(&[0x15, 0x49, 0xA9, 0x66]); // Info
    segment.extend(ebml_size(info.len()));
    segment.extend_from_slice(&info);

    segment.extend_from_slice(&[0x16, 0x54, 0xAE, 0x6B]);
    segment.extend(ebml_size(tracks_body.len()));
    segment.extend_from_slice(&tracks_body);
    segment.extend_from_slice(&[0x1F, 0x43, 0xB6, 0x75]);
    segment.extend(ebml_size(cluster.len()));
    segment.extend_from_slice(&cluster);

    let mut doc = vec![0x1A, 0x45, 0xDF, 0xA3, 0x80, 0x18, 0x53, 0x80, 0x67];
    doc.extend(ebml_size(segment.len()));
    doc.extend_from_slice(&segment);
    doc
}

/// Builds a Matroska / WebM document that genuinely omits `Segment > Info`.
///
/// The counterpart to [`build_webm`], and the only way `CONTAINER.STREAM_DURATION_MISSING`
/// can be reached for a WebM file. Without it, that rule's only WebM coverage
/// would be a fixture that omits the element *by accident*.
#[must_use]
pub fn build_webm_without_duration(
    codec_id: &str,
    track_type: u8,
    blocks: &[(u16, bool, Vec<u8>)],
) -> Vec<u8> {
    // Rebuilding without the Info element rather than stripping it afterwards: the
    // `Info` element sits inside `Segment`, so removing its bytes without fixing
    // `Segment`'s own length would produce a file no reader could parse.
    let mut track_entry = vec![0xD7, 0x81, 1, 0x83, 0x81, track_type, 0x86];
    track_entry.extend(ebml_size(codec_id.len()));
    track_entry.extend_from_slice(codec_id.as_bytes());

    let mut tracks_body = vec![0xAE];
    tracks_body.extend(ebml_size(track_entry.len()));
    tracks_body.extend_from_slice(&track_entry);

    let mut cluster = vec![0xE7, 0x81, 0x00];
    for (rel_ts, is_key, payload) in blocks {
        let mut block = vec![0x81];
        block.extend_from_slice(&rel_ts.to_be_bytes());
        block.push(if *is_key { 0x80 } else { 0x00 });
        block.extend_from_slice(payload);
        cluster.push(0xA3);
        cluster.extend(ebml_size(block.len()));
        cluster.extend_from_slice(&block);
    }

    let mut segment = vec![0x16, 0x54, 0xAE, 0x6B];
    segment.extend(ebml_size(tracks_body.len()));
    segment.extend_from_slice(&tracks_body);
    segment.extend_from_slice(&[0x1F, 0x43, 0xB6, 0x75]);
    segment.extend(ebml_size(cluster.len()));
    segment.extend_from_slice(&cluster);

    let mut doc = vec![0x1A, 0x45, 0xDF, 0xA3, 0x80, 0x18, 0x53, 0x80, 0x67];
    doc.extend(ebml_size(segment.len()));
    doc.extend_from_slice(&segment);
    doc
}

/// Encodes an EBML variable-length size integer for `value`.
///
/// The width is the narrowest that can hold `value`, chosen so that the leading
/// bit of the first byte marks the length. The marker must be stripped by the
/// reader, and a value of all ones in the chosen width means "unknown size",
/// so that one value is unreachable at each width.
///
/// This exists because a single-byte `0x80 | len` is only valid below 127. That
/// is fine for a stub fixture and silently wrong for a real one: at 128 bytes
/// it produces `0x80`, which a reader parses as *unknown size* and swallows
/// the rest of the file. Real encoded video passes 127 bytes in its first
/// cluster almost immediately, so the shortcut corrupts exactly the fixtures
/// that matter.
fn ebml_size(value: usize) -> Vec<u8> {
    for width in 1..=8usize {
        let max = (1usize << (7 * width)) - 1;
        // Skip the all-ones value, which encodes "unknown size".
        if value < max - 1 {
            let marker = 1u32 << (7 * width);
            let encoded = value as u32 | marker;
            return encoded.to_be_bytes()[4 - width..].to_vec();
        }
    }
    // Unreachable for any fixture this crate builds; stated rather than
    // silently truncating.
    panic!("EBML element of {value} bytes exceeds the 8-byte size field");
}

/// Builds an MP4 containing only the header and media data, with no `moov`.
///
/// Used for the missing-index fixture in the corrupt-media corpus (spec §76).
#[must_use]
pub fn build_mp4_without_moov() -> Vec<u8> {
    let mut file = mp4_box(b"ftyp", b"isom\x00\x00\x02\x00isomiso2");
    file.extend_from_slice(&mp4_box(b"mdat", &[0u8; 128]));
    file
}

/// Builds an MP4 whose `moov` box declares no tracks.
#[must_use]
pub fn build_mp4_empty_moov() -> Vec<u8> {
    let mut file = mp4_box(b"ftyp", b"isom\x00\x00\x02\x00isomiso2");
    file.extend_from_slice(&mp4_box(b"moov", &[]));
    file
}

/// Builds an `stss` payload listing `sample_numbers` as sync samples.
///
/// Without this box, ISO-BMFF means *every* sample is a sync sample, which is
/// not what a real encoder writes and would leave GOP analysis untestable.
fn stss(frame_indices: &[u32]) -> Vec<u8> {
    let mut payload = vec![0u8; 4]; // version + flags
    payload.extend_from_slice(&u32be(frame_indices.len() as u32));
    for &frame in frame_indices {
        // `stss` stores 1-based sample numbers; callers pass 0-based indices.
        payload.extend_from_slice(&u32be(frame.saturating_add(1)));
    }
    payload
}

/// Builds a 25 fps MP4 whose keyframe spacing changes partway through.
///
/// The first half uses 50-frame GOPs, the second uses 15-frame GOPs, which is
/// the condition spec §15 describes. Used to prove that GOP analysis surfaces a
/// length change without decoding any frames.
#[must_use]
pub fn build_mp4_stsd_gop_change() -> Vec<u8> {
    build_mp4_with_keyframes(
        &TrackSpec::video_25fps(1920, 1080, 500),
        &gop_change_keyframes(500, 50, 250, 15),
    )
}

/// Keyframe indices for two GOP regimes: `first_gop` up to `switch_at`, then
/// `second_gop` after it.
#[must_use]
pub fn gop_change_keyframes(
    total_frames: u32,
    first_gop: u32,
    switch_at: u32,
    second_gop: u32,
) -> Vec<u32> {
    let mut keyframes: Vec<u32> = Vec::new();
    let mut frame = 0u32;
    while frame < total_frames {
        keyframes.push(frame);
        frame += if frame < switch_at {
            first_gop
        } else {
            second_gop
        };
    }
    keyframes
}

/// Builds an MP4 with an explicit sync-sample table.
#[must_use]
pub fn build_mp4_with_keyframes(track: &TrackSpec, keyframes: &[u32]) -> Vec<u8> {
    build_mp4_multi(&[(
        track,
        TrackExtras {
            sync: SyncTable::Explicit(keyframes),
            ..TrackExtras::default()
        },
    )])
}

/// Builds an MP4 with no `stss` box, meaning every sample is a sync sample.
///
/// All-intra video. Legal, and what `VIDEO.ALL_FRAMES_KEYFRAMES` exists to
/// report — but now asked for explicitly, because omitting `stss` used to be what
/// *every* fixture did by default.
#[must_use]
pub fn build_mp4_without_stss(track: &TrackSpec) -> Vec<u8> {
    build_mp4_multi(&[(
        track,
        TrackExtras {
            sync: SyncTable::AllSync,
            ..TrackExtras::default()
        },
    )])
}

/// Builds a full-box atom carrying a null-terminated string (e.g. `©nam`).
fn text_atom(kind: &[u8; 4], value: &str) -> Vec<u8> {
    let mut body = vec![0u8; 8]; // version + flags, then locale
    body.extend_from_slice(value.as_bytes());
    body.push(0);
    mp4_box(kind, &body)
}

/// Builds an MP4 carrying metadata atoms, including a deliberate cross-scope
/// conflict: `©cmt` appears with two different values, one at container scope
/// and one at track scope.
///
/// Used to prove that metadata extraction and consistency checking work
/// end-to-end on a real container (spec §25, §26).
#[must_use]
pub fn build_mp4_with_metadata(track: &TrackSpec) -> Vec<u8> {
    let base = build_mp4(track);

    // Splice the atoms into the `moov` box: find its header and insert after
    // the existing children.
    let Some(moov_start) = find_box(&base, b"moov") else {
        return base;
    };

    // Container-scope atoms, spliced directly into `moov`.
    let mut injected = Vec::new();
    injected.extend_from_slice(&text_atom(b"\xa9nam", "Synthetic Fixture"));
    injected.extend_from_slice(&text_atom(b"\xa9cmt", "container scope value"));

    let mut out = Vec::with_capacity(base.len() + injected.len() + 64);
    out.extend_from_slice(&base[..moov_start + 8]);
    out.extend_from_slice(&injected);
    out.extend_from_slice(&base[moov_start + 8..]);
    // Every splice must be accounted for in the size chain, or the box walker
    // stops before reaching what was just added.
    grow_box(&mut out, moov_start, injected.len());

    // A track-scope atom carrying the *same key* with a different value. It
    // must go inside `trak`, or the two values would share a scope and would
    // not be a cross-scope conflict at all.
    // 	rak is nested inside moov, so it must be searched for within that
    // payload rather than at the top level.
    let moov_size = moov_len(&out, moov_start);
    let Some(trak_start) = find_box_in(&out, moov_start + 8, moov_start + moov_size, b"trak")
    else {
        return out;
    };
    let track_atom = text_atom(b"\xa9cmt", "track scope value");
    let added = track_atom.len();

    // Splicing bytes into a box changes the sizes of that box and of every
    // ancestor. Without fixing the chain up, the box walker rejects the file
    // and the injected atom is never reached.
    out.splice(trak_start + 8..trak_start + 8, track_atom);
    grow_box(&mut out, trak_start, added);
    grow_box(&mut out, moov_start, added);

    out
}

/// Increases a box's declared size by `amount`.
fn grow_box(bytes: &mut [u8], offset: usize, amount: usize) {
    let current = u32::from_be_bytes([
        bytes[offset],
        bytes[offset + 1],
        bytes[offset + 2],
        bytes[offset + 3],
    ]);
    let grown = current.saturating_add(u32::try_from(amount).unwrap_or(u32::MAX));
    bytes[offset..offset + 4].copy_from_slice(&grown.to_be_bytes());
}

/// Returns the length of the box starting at `offset`.
fn moov_len(bytes: &[u8], offset: usize) -> usize {
    u32::from_be_bytes([
        bytes[offset],
        bytes[offset + 1],
        bytes[offset + 2],
        bytes[offset + 3],
    ]) as usize
}

/// Finds a box of the given type within `[start, end)`, returning its offset.
fn find_box_in(bytes: &[u8], start: usize, end: usize, kind: &[u8; 4]) -> Option<usize> {
    let mut offset = start;
    while offset + 8 <= end.min(bytes.len()) {
        let size = u32::from_be_bytes([
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
        ]) as usize;
        if size < 8 || offset + size > bytes.len() {
            return None;
        }
        if &bytes[offset + 4..offset + 8] == kind {
            return Some(offset);
        }
        offset += size;
    }
    None
}

/// Returns the offset of a top-level box of the given type.
fn find_box(bytes: &[u8], kind: &[u8; 4]) -> Option<usize> {
    let mut offset = 0usize;
    while offset + 8 <= bytes.len() {
        let size = u32::from_be_bytes([
            bytes[offset],
            bytes[offset + 1],
            bytes[offset + 2],
            bytes[offset + 3],
        ]) as usize;
        if size < 8 || offset + size > bytes.len() {
            return None;
        }
        if &bytes[offset + 4..offset + 8] == kind {
            return Some(offset);
        }
        offset += size;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_mp4_av_yields_two_independent_tracks() {
        // The A/V fixture is only useful if it really carries two tracks, each
        // with its own sample tables. A builder that silently produced one
        // would make every A/V assertion below pass vacuously.
        let file = build_mp4_av(
            &TrackSpec::video_25fps(640, 480, 50),
            &TrackSpec::audio_48khz(100),
            0,
        );
        let inspection = crate::mp4::inspect_bytes(file).expect("two-track file parses");
        assert_eq!(inspection.streams.len(), 2, "{:?}", inspection.anomalies);
        assert_eq!(inspection.streams[0].kind.tag(), "video");
        assert_eq!(inspection.streams[1].kind.tag(), "audio");
        // Each track must carry frame timing, or A/V sync has nothing to compare.
        assert!(
            inspection.frame_info[0].is_some(),
            "video frame_info missing"
        );
        assert!(
            inspection.frame_info[1].is_some(),
            "audio frame_info missing"
        );
    }

    #[test]
    fn an_edit_list_does_not_cost_the_track() {
        // Regression. Adding an `elst` used to grow the inner `mdia` box while
        // leaving the enclosing `trak`'s declared size alone, so the demuxer
        // stopped reading at the end of that stale size and reported one stream
        // instead of two — with no anomaly recorded, so nothing looked wrong.
        // An edit list that silently deletes a track is worse than no edit list.
        for delay in [0u32, 40] {
            let f = build_mp4_av(
                &TrackSpec::video_25fps(320, 240, 25),
                &TrackSpec::audio_48khz(500),
                delay,
            );
            let i = crate::mp4::inspect_bytes(f).expect("parses");
            assert_eq!(i.streams.len(), 2, "delay={delay} lost a track");
        }
    }

    #[test]
    fn build_mp4_av_is_deterministic() {
        let a = build_mp4_av(
            &TrackSpec::video_25fps(320, 240, 25),
            &TrackSpec::audio_48khz(50),
            40,
        );
        let b = build_mp4_av(
            &TrackSpec::video_25fps(320, 240, 25),
            &TrackSpec::audio_48khz(50),
            40,
        );
        assert_eq!(a, b);
    }

    #[test]
    fn the_audio_delay_reaches_the_edit_list() {
        // Without a non-zero edit list the two tracks both start at zero and
        // there is no offset to measure.
        let file = build_mp4_av(
            &TrackSpec::video_25fps(320, 240, 25),
            &TrackSpec::audio_48khz(50),
            120,
        );
        let text = String::from_utf8_lossy(&file);
        assert!(
            text.contains("elst"),
            "a delayed audio track must carry an edit list"
        );
    }

    #[test]
    fn build_webm_produces_a_demuxable_document() {
        let bytes = build_webm(
            "V_AV1",
            1,
            &[(0, true, vec![1, 2, 3]), (33, false, vec![4, 5])],
        );
        let inspection = crate::mkv::inspect_bytes(bytes).expect("the builder's output must parse");
        assert_eq!(inspection.format, crate::ContainerFormat::Matroska);
        assert_eq!(inspection.streams.len(), 1);
        assert_eq!(inspection.streams[0].codec.name, "av01");
        let samples = crate::mkv::read_samples(build_webm("V_AV1", 1, &[(0, true, vec![1, 2, 3])]))
            .expect("samples read");
        assert_eq!(samples.len(), 1);
        assert_eq!(samples[0].data, vec![1, 2, 3]);
    }

    #[test]
    fn build_webm_handles_payloads_larger_than_a_single_byte_size_field() {
        // Regression. The builder once wrote every element size as one byte,
        // `0x80 | len`. That is only valid below 127: at 128 it emits `0x80`,
        // which a reader decodes as *unknown size* and therefore swallows the
        // remainder of the file. Stub fixtures never reached the threshold,
        // so only real encoded video exposed it — and when it did, the file
        // simply parsed as an empty track with no error anywhere.
        //
        // These sizes straddle every width boundary a real file crosses.
        for payload_len in [1usize, 126, 127, 128, 300, 16_000, 20_000] {
            let payload = vec![0xABu8; payload_len];
            let bytes = build_webm("V_AV1", 1, &[(0, true, payload.clone())]);
            let samples =
                crate::mkv::read_samples(bytes).unwrap_or_else(|e| panic!("{payload_len}: {e}"));
            assert_eq!(
                samples.len(),
                1,
                "a {payload_len}-byte payload produced {} samples",
                samples.len()
            );
            assert_eq!(
                samples[0].data.len(),
                payload_len,
                "a {payload_len}-byte payload was truncated to {}",
                samples[0].data.len()
            );
        }
    }

    #[test]
    fn ebml_size_round_trips_through_the_demuxer() {
        // Directly exercises the encoder across its width boundaries.
        for value in [0usize, 1, 126, 127, 128, 16_382, 16_383, 16_384] {
            let encoded = ebml_size(value);
            // The leading marker bit position determines the width a reader
            // infers; recompute the value the way the demuxer does.
            let first = encoded[0];
            let width = first.leading_zeros() as usize + 1;
            assert_eq!(
                width,
                encoded.len(),
                "value {value}: marker disagrees with width"
            );
            let mut recovered = u64::from(first & (0xFF >> width));
            for &b in &encoded[1..] {
                recovered = (recovered << 8) | u64::from(b);
            }
            assert_eq!(recovered, value as u64, "value {value} did not round trip");
        }
    }

    #[test]
    fn build_webm_is_deterministic() {
        // Spec §77: a fixture must regenerate byte-identically everywhere.
        let a = build_webm("V_VP9", 1, &[(0, true, vec![9])]);
        let b = build_webm("V_VP9", 1, &[(0, true, vec![9])]);
        assert_eq!(a, b);
    }

    #[test]
    fn build_webm_with_no_blocks_still_parses() {
        let bytes = build_webm("V_VP9", 1, &[]);
        let inspection = crate::mkv::inspect_bytes(bytes).expect("an empty cluster must parse");
        assert_eq!(inspection.streams.len(), 1);
        assert!(inspection.frame_info[0].is_none());
    }

    #[test]
    fn generated_file_has_an_ftyp_signature() {
        let file = build_mp4(&TrackSpec::video_25fps(1920, 1080, 50));
        assert_eq!(&file[4..8], b"ftyp");
    }

    #[test]
    fn generation_is_deterministic() {
        // Fixtures must be byte-identical across runs (spec §77).
        let spec = TrackSpec::video_25fps(640, 480, 25);
        assert_eq!(build_mp4(&spec), build_mp4(&spec));
    }

    #[test]
    fn sample_count_matches_the_timing_table() {
        let spec = TrackSpec {
            timing: vec![(25, 1), (25, 2)],
            ..TrackSpec::video_25fps(640, 480, 50)
        };
        assert_eq!(spec.sample_count(), 50);
    }

    #[test]
    fn corpus_fixtures_are_distinct_from_each_other() {
        assert_ne!(build_mp4_without_moov(), build_mp4_empty_moov());
        assert_ne!(
            build_mp4_without_moov(),
            build_mp4(&TrackSpec::audio_48khz(10))
        );
    }
}
