//! Synthetic media generation for the test corpus (spec §76).
//!
//! Building fixtures in code rather than checking in binary blobs keeps the
//! repository free of opaque media and, more importantly, makes each structural
//! feature under test visible in the source: a failing test points directly at
//! the box that was meant to be malformed.
//!
//! It also removes the need for an external encoder. The corrupt-media corpus
//! can be regenerated byte-identically on any machine, which matters because
//! those fixtures must be deterministic (spec §77).

#![allow(clippy::too_many_arguments)]

/// Writes a big-endian u32.
fn u32be(value: u32) -> [u8; 4] {
    value.to_be_bytes()
}

/// Writes a big-endian u16.
fn u16be(value: u16) -> [u8; 2] {
    value.to_be_bytes()
}

/// Wraps `payload` in a box of the given four-character type.
fn mp4_box(kind: &[u8; 4], payload: &[u8]) -> Vec<u8> {
    let mut out = u32be((payload.len() + 8) as u32).to_vec();
    out.extend_from_slice(kind);
    out.extend_from_slice(payload);
    out
}

/// Builds an `stsd` payload declaring one visual or audio sample entry.
fn stsd(handler: &[u8; 4], width: u16, height: u16) -> Vec<u8> {
    let mut entry = vec![0u8; 6]; // reserved
    entry.extend_from_slice(&u16be(1)); // data_reference_index
    entry.extend_from_slice(&[0u8; 6]); // pre_defined / reserved
    entry.extend_from_slice(&u16be(width));
    entry.extend_from_slice(&u16be(height));
    entry.extend_from_slice(&[0u8; 50]); // remaining visual fields

    let mut payload = vec![0u8; 4];
    payload.extend_from_slice(&u32be(1)); // entry_count
    payload.extend_from_slice(handler);
    payload.extend_from_slice(&mp4_box(b"esds", &[0u8; 4]));
    payload.extend_from_slice(&entry);
    payload
}

/// Builds an `stsc` payload mapping one chunk to all samples.
fn stsc(sample_count: u32) -> Vec<u8> {
    let mut out = vec![0u8; 4];
    out.extend_from_slice(&u32be(1)); // entry_count
    out.extend_from_slice(&u32be(1)); // first_chunk
    out.extend_from_slice(&u32be(sample_count));
    out.extend_from_slice(&u32be(1)); // sample_description_index
    out
}

/// A description of the synthetic track to generate.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrackSpec {
    /// ISO-BMFF handler type: `vide`, `soun`, or anything else.
    pub handler: [u8; 4],
    /// Coded width in pixels.
    pub width: u16,
    /// Coded height in pixels.
    pub height: u16,
    /// Track timescale, in ticks per second.
    pub timescale: u32,
    /// Time-to-sample runs as `(sample_count, sample_delta)` pairs.
    ///
    /// More than one entry models a track whose cadence changes, which is a
    /// forensic condition rather than an error.
    pub timing: Vec<(u32, u32)>,
}

impl TrackSpec {
    /// A 25 fps video track of `frames` frames.
    #[must_use]
    pub fn video_25fps(width: u16, height: u16, frames: u32) -> Self {
        Self {
            handler: *b"vide",
            width,
            height,
            timescale: 25,
            timing: vec![(frames, 1)],
        }
    }

    /// A 48 kHz audio track.
    #[must_use]
    pub fn audio_48khz(frames: u32) -> Self {
        Self {
            handler: *b"soun",
            width: 0,
            height: 0,
            timescale: 48_000,
            timing: vec![(frames, 1)],
        }
    }

    /// Returns the total number of samples this track declares.
    #[must_use]
    pub fn sample_count(&self) -> u32 {
        self.timing.iter().map(|(count, _)| count).sum()
    }
}

/// Builds a single-track MP4 file for the given track.
///
/// # Panics
///
/// Never. Every field is bounded by the caller; box sizes are checked against
/// `u32::MAX` by construction because the payload is built in memory.
#[must_use]
pub fn build_mp4(track: &TrackSpec) -> Vec<u8> {
    let sample_count = track.sample_count();
    let total_duration: u64 = track
        .timing
        .iter()
        .map(|(count, delta)| u64::from(*count) * u64::from(*delta))
        .sum();

    let mut stts_payload = vec![0u8; 4];
    stts_payload.extend_from_slice(&u32be(track.timing.len() as u32));
    for (count, delta) in &track.timing {
        stts_payload.extend_from_slice(&u32be(*count));
        stts_payload.extend_from_slice(&u32be(*delta));
    }

    let mut stsz_payload = vec![0u8; 4];
    stsz_payload.extend_from_slice(&u32be(0)); // sample_size (0 = variable)
    stsz_payload.extend_from_slice(&u32be(sample_count));
    for _ in 0..sample_count {
        stsz_payload.extend_from_slice(&u32be(100));
    }

    let mut stco_payload = vec![0u8; 4];
    stco_payload.extend_from_slice(&u32be(1)); // entry_count
    stco_payload.extend_from_slice(&u32be(0)); // chunk offset

    let mut mdhd = vec![0u8; 4];
    mdhd.extend_from_slice(&u32be(0));
    mdhd.extend_from_slice(&u32be(0));
    mdhd.extend_from_slice(&u32be(track.timescale));
    mdhd.extend_from_slice(&u32be(total_duration.min(u64::from(u32::MAX)) as u32));
    mdhd.extend_from_slice(&u32be(0x55C4)); // language 'und'
    mdhd.extend_from_slice(&u16be(0));

    let mut hdlr = vec![0u8; 4];
    hdlr.extend_from_slice(&u32be(0));
    hdlr.extend_from_slice(&track.handler);
    hdlr.extend_from_slice(&[0u8; 12]);
    hdlr.extend_from_slice(b"VideoHandler\0");

    let mut mvhd = vec![0u8; 4];
    mvhd.extend_from_slice(&u32be(0));
    mvhd.extend_from_slice(&u32be(0));
    mvhd.extend_from_slice(&u32be(1000));
    mvhd.extend_from_slice(&u32be(0));
    mvhd.extend_from_slice(&[0u8; 80]);

    let mut tkhd = vec![0u8; 4];
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(1));
    tkhd.extend_from_slice(&u32be(0));
    tkhd.extend_from_slice(&u32be(total_duration.min(u64::from(u32::MAX)) as u32));
    tkhd.extend_from_slice(&[0u8; 8]);
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&u16be(0));
    tkhd.extend_from_slice(&[0u8; 36]);
    tkhd.extend_from_slice(&u32be(u32::from(track.width) << 16));
    tkhd.extend_from_slice(&u32be(u32::from(track.height) << 16));

    let stbl = {
        let mut boxes = mp4_box(b"stsd", &stsd(&track.handler, track.width, track.height));
        boxes.extend_from_slice(&mp4_box(b"stts", &stts_payload));
        boxes.extend_from_slice(&mp4_box(b"stsc", &stsc(sample_count)));
        boxes.extend_from_slice(&mp4_box(b"stsz", &stsz_payload));
        boxes.extend_from_slice(&mp4_box(b"stco", &stco_payload));
        mp4_box(b"stbl", &boxes)
    };

    let minf = {
        let mut inner = mp4_box(b"vmhd", &[0u8; 12]);
        inner.extend_from_slice(&stbl);
        mp4_box(b"minf", &inner)
    };

    let mdia = {
        let mut inner = mp4_box(b"mdhd", &mdhd);
        inner.extend_from_slice(&mp4_box(b"hdlr", &hdlr));
        inner.extend_from_slice(&minf);
        mp4_box(b"mdia", &inner)
    };

    let trak = {
        let mut inner = mp4_box(b"tkhd", &tkhd);
        inner.extend_from_slice(&mdia);
        mp4_box(b"trak", &inner)
    };

    let moov = {
        let mut inner = mp4_box(b"mvhd", &mvhd);
        inner.extend_from_slice(&trak);
        mp4_box(b"moov", &inner)
    };

    let mut file = mp4_box(b"ftyp", b"isom\x00\x00\x02\x00isomiso2avc1mp41");
    file.extend_from_slice(&moov);
    file.extend_from_slice(&mp4_box(b"mdat", &vec![0u8; 64]));
    file
}

/// Builds an MP4 containing only the header and media data, with no `moov`.
///
/// Used for the missing-index fixture in the corrupt-media corpus (spec §76).
#[must_use]
pub fn build_mp4_without_moov() -> Vec<u8> {
    let mut file = mp4_box(b"ftyp", b"isom\x00\x00\x02\x00isomiso2");
    file.extend_from_slice(&mp4_box(b"mdat", &vec![0u8; 128]));
    file
}

/// Builds an MP4 whose `moov` box declares no tracks.
#[must_use]
pub fn build_mp4_empty_moov() -> Vec<u8> {
    let mut file = mp4_box(b"ftyp", b"isom\x00\x00\x02\x00isomiso2");
    file.extend_from_slice(&mp4_box(b"moov", &[]));
    file
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_file_has_an_ftyp_signature() {
        let file = build_mp4(&TrackSpec::video_25fps(1920, 1080, 50));
        assert_eq!(&file[4..8], b"ftyp");
    }

    #[test]
    fn generation_is_deterministic() {
        // Fixtures must be byte-identical across runs (spec §77).
        let spec = TrackSpec::video_25fps(640, 480, 25);
        assert_eq!(build_mp4(&spec), build_mp4(&spec));
    }

    #[test]
    fn sample_count_matches_the_timing_table() {
        let spec = TrackSpec {
            timing: vec![(25, 1), (25, 2)],
            ..TrackSpec::video_25fps(640, 480, 50)
        };
        assert_eq!(spec.sample_count(), 50);
    }

    #[test]
    fn corpus_fixtures_are_distinct_from_each_other() {
        assert_ne!(build_mp4_without_moov(), build_mp4_empty_moov());
        assert_ne!(build_mp4_without_moov(), build_mp4(&TrackSpec::audio_48khz(10)));
    }
}